<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LED Editor - 64x64 Matrix</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Background Animation -->
    <div class="bg-animation">
        <div class="bg-square" style="top: 10%; left: 10%; width: 100px; height: 100px; animation-duration: 8s;"></div>
        <div class="bg-square" style="top: 70%; left: 80%; width: 150px; height: 150px; animation-duration: 12s;"></div>
        <div class="bg-square" style="top: 40%; left: 40%; width: 80px; height: 80px; animation-duration: 6s;"></div>
        <div class="bg-square" style="top: 20%; left: 60%; width: 120px; height: 120px; animation-duration: 15s;"></div>
        <div class="bg-square" style="top: 80%; left: 20%; width: 60px; height: 60px; animation-duration: 9s;"></div>
    </div>

    <nav>
        <a href="index.php" class="logo">LED Matrix</a>
        <ul>
            <li><a href="public.php">Gallery</a></li>
            <li><a href="editor.php" class="active">Editor</a></li>
            <li id="authLink"><a href="login.php" class="btn-nav">Login</a></li>
        </ul>
    </nav>

    <div class="container">
        <h1>Design Editor</h1>
        
        <div class="main-editor-container">
            <!-- Controls -->
            <div class="controls">
                <h3>Settings</h3>
                <div class="control-group">
                    <label>Grid Size</label>
                    <div style="display: flex; gap: 10px;">
                        <input type="number" id="gridWidth" value="16" min="8" max="64" placeholder="W">
                        <input type="number" id="gridHeight" value="16" min="8" max="64" placeholder="H">
                    </div>
                    <button id="resizeBtn" class="secondary-btn" style="margin-top: 5px;">Apply Size</button>
                </div>

                <div class="control-group">
                    <label for="colorPicker">Color</label>
                    <input type="color" id="colorPicker" value="#ff0000">
                </div>

                <div class="control-group">
                    <label>Tools</label>
                    <div style="display: flex; gap: 5px; margin-bottom: 10px;">
                        <button id="pencilBtn" class="tool-btn active" title="Pencil">✏️</button>
                        <button id="eraserBtn" class="tool-btn" title="Eraser">🧹</button>
                        <button id="bucketBtn" class="tool-btn" title="Fill Bucket">🪣</button>
                    </div>
                    
                    <label>Brush Size</label>
                    <div style="display: flex; gap: 5px; margin-bottom: 10px;">
                        <button class="size-btn active" data-size="1">1x</button>
                        <button class="size-btn" data-size="2">2x</button>
                        <button class="size-btn" data-size="3">3x</button>
                    </div>

                    <button id="clearBtn" class="clear-btn">Clear Matrix</button>
                    
                    <label style="margin-top: 10px;">Import Image</label>
                    <div class="file-input-wrapper">
                        <button class="file-input-btn">Choose File</button>
                        <input type="file" id="imageInput" accept="image/*">
                    </div>
                </div>

                <div class="control-group">
                    <label for="designName">Save Design</label>
                    <input type="text" id="designName" placeholder="Design Name...">
                    <div style="margin-top: 5px;">
                        <input type="checkbox" id="isPublic"> <label for="isPublic" style="display:inline; font-weight:normal;">Public Gallery</label>
                    </div>
                    <button id="saveBtn" style="margin-top: 10px;">Save Design</button>
                </div>
            </div>

            <!-- LED Matrix -->
            <div class="matrix-container">
                <div class="led-grid" id="ledGrid">
                    <!-- Grid generated by JS -->
                </div>
            </div>

            <!-- Saved Designs -->
            <div class="controls" style="max-height: 600px; display: flex; flex-direction: column;">
                <h3>Library</h3>
                <div style="display: flex; gap: 5px; margin-bottom: 10px;">
                    <button id="tabMy" class="secondary-btn" style="flex:1; padding: 5px; font-size: 0.9em;">My</button>
                    <button id="tabFav" class="secondary-btn" style="flex:1; background: #333; padding: 5px; font-size: 0.9em;">Favs</button>
                    <button id="tabPublic" class="secondary-btn" style="flex:1; background: #333; padding: 5px; font-size: 0.9em;">Gallery</button>
                </div>
                <div id="designList" class="design-list" style="flex: 1; overflow-y: auto;">
                    <!-- Designs loaded from API -->
                    <div class="design-item">Loading...</div>
                </div>
            </div>
        </div>
    </div>

    <script src="background.js"></script>
    <script src="script.js"></script>
    <script>
        // Check auth for navbar
        fetch('auth.php?action=check')
            .then(res => res.json())
            .then(data => {
                if (data.logged_in) {
                    const authLink = document.getElementById('authLink');
                    authLink.innerHTML = `<a href="#" onclick="logout()" class="btn-nav">Logout</a>`;
                } else {
                    // Optional: Redirect to login if editor requires auth? 
                    // For now, let them play but fail to save if not logged in.
                }
            });

        function logout() {
            fetch('auth.php?action=logout', { method: 'POST' })
                .then(() => window.location.reload());
        }
    </script>
</body>
</html>
